
spring:
  application:
    name: basket
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce-microservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: omeR%50hajk
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8093
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
